---
  - name: Instalacao mysql
    apt:
      pkg:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
      
      update_cache: yes

  - name: Criando usuario no banco mysql
    mysql_user:
        name: "wp@user"
        password: "wp@passwd"
        priv: '*.*:ALL'
        host: "%"
        state: present

  - name: Criando database wordpress
    mysql_db:
        name: "wordpress"
        state: present